NewsPortal/NewsPortal/urls.py
from django.urls import path

from .views import (
    PostList, PostDetail, SearchResults, NewsCreate, ArticlesCreate, NewsUpdate, ArticlesUpdate, NewsDelete,
    ArticlesDelete, NewsList, ArticlesList, NewsDetail, ArticlesDetail, upgrade_user
)

urlpatterns = [
    path('', PostList.as_view(), name='posts'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search/', SearchResults.as_view(), name='search'),
    path('upgrade/', upgrade_user, name='account_upgrade'),
    path('news/', NewsList.as_view(), name='news'),
    path('news/<int:pk>', NewsDetail.as_view(), name='news_detail'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', NewsUpdate.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/', ArticlesList.as_view(), name='articles'),
    path('articles/<int:pk>', ArticlesDetail.as_view(), name='articles_detail'),
    path('articles/create/', ArticlesCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', ArticlesUpdate.as_view(), name='articles_update'),
    path('articles/<int:pk>/delete/', ArticlesDelete.as_view(), name='articles_delete'),
]

NewsPortal/NewsPortal_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include("allauth.urls")),
    path('posts/', include('NewsPortal.urls')),
]

NewsPortal/NewsPortal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
	author = models.OneToOneField(User, on_delete=models.CASCADE)
	rating_author = models.IntegerField(default=0)

	def update_rating(self):
		author_post_rating = self.post_set.aggregate(sum_post_rating=Sum('rating'))
		post_rating = author_post_rating.get('sum_post_rating')

		author_comment_rating = self.comment_set.aggregate(sum_comment_rating=Sum('rating'))
		comment_rating = author_comment_rating.get('sum_comment_rating')

		author_comm_post_rating = self.post_set.aggregate(sum_comm_post_rating=Sum('rating'))
		comm_post_rating = author_comm_post_rating.get('sum_comm_post_rating')

		self.rating_author = post_rating * 3 + comment_rating + comm_post_rating
		self.save()


class Category(models.Model):
	category = models.CharField(max_length=64, unique=True)

	def __str__(self):
		return self.category.title()


class Post(models.Model):
	article = 'AR'
	news = 'NW'

	TYPE = [
		(article, 'Статья'),
		(news, 'Новость')
	]

	type_post = models.CharField(max_length=2, choices=TYPE, default='NW')
	time_in = models.DateTimeField(auto_now_add=True)
	headline = models.CharField(max_length=128,)
	text = models.TextField()
	rating = models.IntegerField(default=0)
	to_author = models.ForeignKey(Author, on_delete=models.CASCADE)
	to_many_category = models.ManyToManyField(Category, through='PostCategory', related_name='n')

	def preview(self):
		return self.text[:20] + '...'
		# return f'{self.text[0:2] + "..."}'
		# return '{}'.format(self.text[0:128] + '...')

	def like_post(self):
		self.rating += 1
		self.save()

	def dislike_post(self):
		self.rating -= 1
		self.save()

	def __str__(self):
		return f'{self.headline}: {self.text[:20]}'

	def get_absolute_url(self):
		return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
	to_post = models.ForeignKey(Post, on_delete=models.CASCADE)
	to_category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
	text = models.TextField()
	time_in = models.DateTimeField(auto_now_add=True)
	rating = models.IntegerField(default=0)
	comm_post = models.ForeignKey(Post, on_delete=models.CASCADE)
	comm_user = models.ForeignKey(User, on_delete=models.CASCADE)

	def like_comm(self):
		self.rating += 1
		self.save()

	def dislike_comm(self):
		self.rating -= 1
		self.save()

NewsPortal/templates/account_upgrade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NewsPortal/templates/articles.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Все статьи
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>Все посты в категории статьи</h1>
    <h3>Всего статей: {{ articles|length }}</h3>
    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о новых статьях!" }} </h3>

    <hr>

    {% if perms.NewsPortal.add_post %}
    <a href="{% url 'articles_create' %}">Создать новый пост</a>
    {% endif %}

    {% if articles %}
        <table>
            <tr>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Превью</th>
                {% if perms.NewsPortal.change_post %}
                <td>Действия</td>
                {% endif %}

            </tr>
            {% for n in articles %}
            <tr>
                <td>{{ n.headline }}</td>
                <td>{{ n.time_in|date:'d M Y'  }}</td>
                <td>{{ n.preview }}</td>
                <td>
                    {% if perms.NewsPortal.change_post %}
                    <a href="{% url 'articles_update' pk=n.id %}">Изменить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Статей нет! Вообще нет!</h2>
    {% endif %}

    {% if page_obj.previous_page_number == 1 %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?{% url_replace page=1 %}">
        Начало
    </a>
    ...
    <a href="?page={% url_replace page=page_obj.previous_page_number %}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={% url_replace page=page_obj.next_page_number %}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={% url_replace page=paginator.num_page %}">
                Конец
            </a>
        {% endif %}
    {% endif %}

{% endblock content%}
</body>
</html>

NewsPortal/templates/articles_create.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/articles_delete.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  <p>Удаляем "{{ object.name }}"?</p>
  <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/articles_detail.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Articles_detail
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>{{ post.headline }}</h1>
    <h5>{{ post.time_in|date:'d M Y' }}</h5>
    <hr>
    <h4>{{ post.text|censor }}</h4>
{% endblock content%}
</body>
</html>

NewsPortal/templates/articles_update.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/news.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Все новости
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>Все посты в категории новости</h1>
    <h3>Всего новостей: {{ news|length }}</h3>
    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о новостях!" }} </h3>

    <hr>

    {% if perms.NewsPortal.add_post %}
    <a href="{% url 'news_create' %}">Создать новый пост</a>
    {% endif %}

    {% if news %}
        <table>
            <tr>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Превью</th>
                {% if perms.NewsPortal.change_post %}
                <td>Действия</td>
                {% endif %}

            </tr>
            {% for n in news %}
            <tr>
                <td>{{ n.headline }}</td>
                <td>{{ n.time_in|date:'d M Y'  }}</td>
                <td>{{ n.preview }}</td>
                <td>
                    {% if perms.NewsPortal.change_post %}
                    <a href="{% url 'news_update' pk=n.id %}">Изменить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет! Вообще нет!</h2>
    {% endif %}

    {% if page_obj.previous_page_number == 1 %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?{% url_replace page=1 %}">
        Начало
    </a>
    ...
    <a href="?page={% url_replace page=page_obj.previous_page_number %}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={% url_replace page=page_obj.next_page_number %}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={% url_replace page=paginator.num_page %}">
                Конец
            </a>
        {% endif %}
    {% endif %}

{% endblock content%}
</body>
</html>

NewsPortal/templates/news_create.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/news_delete.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  <p>Удаляем "{{ object.name }}"?</p>
  <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/news_detail.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        News_detail
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>{{ post.headline }}</h1>
    <h5>{{ post.time_in|date:'d M Y' }}</h5>
    <hr>
    <h4>{{ post.text|censor }}</h4>
{% endblock content%}
</body>
</html>

NewsPortal/templates/news_update.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/post_detail.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Post_detail
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>{{ post.headline }}</h1>
    <h5>{{ post.time_in|date:'d M Y' }}</h5>
    <hr>
    <h4>{{ post.text|censor }}</h4>
{% endblock content%}
</body>
</html>

NewsPortal/templates/posts.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Posts
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <h1>Все новости</h1>
    <h3>Всего новостей: {{ posts|length }}</h3>
    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о новостях!" }} </h3>

    <hr>
    {% if not is_author %}
    <button>
        <a class="nav-link" href="{% url 'account_upgrade' %}">
            <h4><strong>Join the authors!</strong></h4>
        </a>
    </button>
    {% endif %}
    {% if posts %}
        <table>
            <tr>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Превью</th>
            </tr>
            {% for n in posts %}
            <tr>
                <td>{{ n.headline }}</td>
                <td>{{ n.time_in|date:'d M Y'  }}</td>
                <td>{{ n.preview }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет! Вообще нет!</h2>
    {% endif %}

    {% if page_obj.previous_page_number == 1 %}
    <a href="?page=1">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?page=1">
        Начало
    </a>
    ...
    <a href="?page={{ page_obj.previous_page_number }}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ paginator.num_page }}">
                Конец
            </a>
        {% endif %}
    {% endif %}

{% endblock content%}
</body>
</html>

NewsPortal/templates/search.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Поиск
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

<!--    <label for="meeting-time">Choose a time for your appointment:</label>-->

<!--    <input-->
<!--      type="datetime-local"-->
<!--      id="meeting-time"-->
<!--      name="meeting-time"-->
<!--      value="2018-06-12T19:30"-->
<!--      min="2018-06-07T00:00"-->
<!--      max="2018-06-14T00:00"-->
<!--    />-->

    <hr>
    {% if search %}
        <table>
            <tr>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Превью</th>
            </tr>
            {% for n in search %}
            <tr>
                <td>{{ n.headline }}</td>
                <td>{{ n.time_in|date:'d M Y'  }}</td>
                <td>{{ n.preview }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет! Вообще нет!</h2>
    {% endif %}

    {% if page_obj.previous_page_number == 1 %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?{% url_replace page=1 %}">
        Начало
    </a>
    ...
    <a href="?page={% url_replace page=page_obj.previous_page_number %}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={% url_replace page=page_obj.next_page_number %}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={% url_replace page=paginator.num_page %}">
                Конец
            </a>
        {% endif %}
    {% endif %}

{% endblock content%}
</body>
</html>